server:
  port: 8888
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    api-gateway:
      path: /api-gateway/**
      serviceId: eureka-client